name: Run the Training pipeline

on:
  push:
    branches: [ run-pipeline ]
  workflow_dispatch:
    
jobs:
  run-zenml-training-pipeline:
    runs-on: ubuntu-latest
    env:
      ZENML_STORE_URL:  ${{ secrets.ZENML_STORE_URL }}
      ZENML_STORE_API_KEY: ${{ secrets.ZENML_API_KEY }}
      ZENML_PROJECT: default
      ZENML_STACK: ml_forecast_stack
      ZENML_CODE_REPOSITORY_IGNORE_UNTRACKED_FILES: True

    steps:
    - uses: actions/checkout@v4
        
    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: GCP auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Setup gcloud CLI with gke plugin
      uses: "google-github-actions/setup-gcloud@v2"
      with:
        install_components: "gke-gcloud-auth-plugin"
    
    
    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker australia-southeast1-docker.pkg.dev --quiet
          
    - name: Install dependencies
      run: |
        uv sync --locked
    
    - name: Connect to Kubernetes cluster
      run: |
        make connect-k8s-cluster

    - name: Login to ZenML server
      run: |
        uv run zenml project set ${{ env.ZENML_PROJECT }}

    - name: Set stack
      run: |
        uv run zenml stack set ${{ env.ZENML_STACK }}

    - name: List files
      run: |
       find . -type f

    - name: Check git status
      run: |
       git status

    - name: Check Zenml status
      run: |
        uv run zenml status
        echo $ZENML_CODE_REPOSITORY_IGNORE_UNTRACKED_FILES

    - name: Run training pipeline
      run: |
        make run-training-pipeline